# Generated by Django 5.2.1 on 2025-05-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('can_view_todo', 'Can view todo'), ('can_edit_todo', 'Can edit todo')]},
        ),
    ]
