# Generated by Django 5.2.1 on 2025-05-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('can_view_all_todo', 'can view all todo item'), ('can_manage_all_todo', 'can update, delete and create todo item')]},
        ),
    ]
